<?php
/**
 * Plugin Mobile for Roundcube
 *
 * Add new skin mobile to Roundcube
 *
 * Copyright (C) 2015  PNE Annuaire et Messagerie/MEDDE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author PNE Annuaire et Messagerie/MEDDE
 * @license GNU GPLv3+
 *
 * Translated by Briesmi
 */

$labels = array();
$labels['mobile'] = 'Mobile Ansicht';
$labels['desktop'] = 'Desktop Ansicht';
$labels['pull_to_refresh'] = 'Zum aktualisieren ziehen';
$labels['release_to_refresh'] = 'Zum aktualisieren loslassen';
$labels['slide to delete message'] = 'Wischen um Nachricht zu löschen';
$labels['release to delete message'] = 'Loslassen um Nachricht zu löschen';
$labels['slide to mark as read'] = 'Wischen um als gelesen zu markieren';
$labels['release to mark as read'] = 'Loslassen um als gelesen zu markieren';
$labels['slide to mark as unread'] = 'Wischen um als ungelesen zu markieren';
$labels['release to mark as unread'] = 'Loslassen um als ungelesen zu markieren';

// Enigma
$messages['addenigmapass'] = 'Anklicken um das Key Password hinzuzufügen.';
