<?php
/**
 * Plugin Mobile for Roundcube
 *
 * Add new skin mobile to Roundcube
 *
 * Copyright (C) 2015  PNE Annuaire et Messagerie/MEDDE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author PNE Annuaire et Messagerie/MEDDE
 * @author gaguileram
 * @license GNU GPLv3+
 *
 */

$labels = array();
$labels['mobile'] = 'Vista móvil';
$labels['desktop'] = 'Vista escritorio';
$labels['pull_to_refresh'] = 'Pulsar para refrescar';
$labels['release_to_refresh'] = 'Soltar para refrescar';
$labels['slide to delete message'] = 'Deslizar para borrar mensaje';
$labels['release to delete message'] = 'Soltar para borrar mensaje';
$labels['slide to mark as read'] = 'Deslizar para marcar como leído';
$labels['release to mark as read'] = 'Soltar para marcar como leído';
$labels['slide to mark as unread'] = 'Deslizar para marcar como no leído';
$labels['release to mark as unread'] = 'Soltar para marcar como no leído';

// Enigma
$messages['addenigmapass'] = 'Haga clic para agregar la clave de contraseña.';