<?php
/**
 * Plugin Mobile for Roundcube
 *
 * Add new skin mobile to Roundcube
 *
 * Copyright (C) 2015  PNE Annuaire et Messagerie/MEDDE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author PNE Annuaire et Messagerie/MEDDE
 * @license GNU GPLv3+
 *
 * Translated by Gianluca Giacometti
 */

$labels = array();
$labels['mobile'] = 'Vista mobile';
$labels['desktop'] = 'Vista desktop';
$labels['pull_to_refresh'] = 'Scorri verso il basso per aggiornare';
$labels['release_to_refresh'] = 'Rilascia per aggiornare';
$labels['slide to delete message'] = 'Scorri lateralmente per cancellare il messaggio';
$labels['release to delete message'] = 'Rilascia per cancellare il messaggio';
$labels['slide to mark as read'] = 'Scorri lateralmente per segnare il messaggio come letto';
$labels['release to mark as read'] = 'Rilascia per impostare il messaggio come letto';
$labels['slide to mark as unread'] = 'Scorri lateralmente per segnare il messaggio come non letto';
$labels['release to mark as unread'] = 'Rilascia per segnare il messaggio come non letto';

// Enigma
$messages['addenigmapass'] = 'Clicca per aggiungere la password.';
