<?php
/**
 * Plugin Mobile for Roundcube
 *
 * Add new skin mobile to Roundcube
 *
 * Copyright (C) 2015  PNE Annuaire et Messagerie/MEDDE
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * @author PNE Annuaire et Messagerie/MEDDE
 * @license GNU GPLv3+
 *
 */

$labels = array();
$labels['mobile'] = 'Мобильная версия';
$labels['desktop'] = 'Полная версия';
$labels['pull_to_refresh'] = 'Потяните вниз для обновления';
$labels['release_to_refresh'] = 'Отпустите для обновления';
$labels['slide to delete message'] = 'Передвиньте, чтобы удалить сообщения';
$labels['release to delete message'] = 'Отпустите, чтобы удалить сообщения';
$labels['slide to mark as read'] = 'Передвиньте, чтобы отметить прочитанным';
$labels['release to mark as read'] = 'Отпусите, чтобы отметить прочитанным';
$labels['slide to mark as unread'] = 'Передвиньте, чтобы отметить непрочитанным';
$labels['release to mark as unread'] = 'Отпустите, чтобы отметить непрочитанным';
